# Generated by Django 3.2.7 on 2021-11-24 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEstufa',
            fields=[
                ('id_dados_estufa', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('valor', models.CharField(blank=True, max_length=50)),
                ('slots', models.CharField(blank=True, max_length=2)),
                ('fileiras', models.CharField(blank=True, max_length=2)),
                ('itensInclusos', models.CharField(blank=True, max_length=255)),
                ('altura_cm', models.CharField(blank=True, max_length=10)),
                ('largura_cm', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'dados_estufa',
            },
        ),
        migrations.CreateModel(
            name='EnderecosDeEntrega',
            fields=[
                ('id_endereco_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('rua', models.CharField(blank=True, max_length=255)),
                ('casa', models.CharField(blank=True, max_length=10)),
                ('cep', models.CharField(blank=True, max_length=12)),
                ('bairro', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(blank=True, max_length=255)),
                ('pais', models.CharField(blank=True, max_length=255)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dados_entrega',
            },
        ),
        migrations.CreateModel(
            name='TabelasDadosUsuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('senha', models.CharField(blank=True, max_length=225)),
                ('telefone', models.CharField(blank=True, max_length=11)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(blank=True, max_length=255)),
                ('pais', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('id_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dados_usuario',
            },
        ),
        migrations.CreateModel(
            name='TabelasDadosCompra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateField(auto_now=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=255)),
                ('id_entrega', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginas.enderecosdeentrega')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginas.dadosestufa')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dados_compra',
            },
        ),
    ]
