# Generated by Django 3.2.7 on 2021-11-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelasdadosusuario',
            name='senha',
        ),
        migrations.AlterField(
            model_name='tabelasdadosusuario',
            name='pais',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
