# Generated by Django 3.2.7 on 2021-11-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_auto_20211126_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosestufa',
            name='comprimento_cm',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dadosestufa',
            name='estrurura',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
