# Generated by Django 3.2.7 on 2021-11-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_auto_20211126_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosestufa',
            old_name='estrurura',
            new_name='estrutura',
        ),
    ]
