# Generated by Django 3.2.7 on 2021-11-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_rename_estrurura_dadosestufa_estrutura'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosestufa',
            name='referencia',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
